spring:
    application:
        name: organization-service

server:
    port: 0

management:
    endpoint:
        features:
            enabled: true
        refresh:
            enabled: true
    endpoints:
        web:
            exposure:
                include: refresh
